version: '3.9'

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: neuniverso_web
    restart: always
    env_file:
      - ../../.env
    ports:
      - '3000:3000'
    networks:
      - neunet

  nginx:
    image: nginx:alpine
    container_name: neuniverso_nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ../../infrastructure/docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - neunet

networks:
  neunet:
    driver: bridge
